### PR TITLE
Fix import-scope with `lodash/fp` (fixes #134)

### LINKED ISSUE #134: import-scope false positive with `lodash/fp`
When using the `member` import style with the `import-scope` rule, imports from `lodash/fp` are incorrectly marked as errors.  E.g., 

```js
import {
    filter as fpFilter,
    map as fpMap,
} from 'lodash/fp'
```

reports `Import members from the full lodash module`

IIRC, `fp` will be moved to a different module in the next lodash major version, but for now I think this is incorrect behavior?  If agreed, I can probably work up a PR to fix it.

### PR DESCRIPTION
**Pull request by SpainTrain**
- Fixed false positives when using import-scope with lodash-fp

closes #134

### CODE REVIEW

**Comment by SpainTrain** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wix/eslint-plugin-lodash/135)*

File: tests/lib/rules/import-scope.js [hunk 1]
```diff
@@ -29,67 +29,85 @@ const testCases = {
...
             import: [
                 "import _ from 'lodash'",
                 "import * as _ from 'lodash'",
-                "import {someMember} from 'some-other-module'"
+                "import {someMember} from 'some-other-module'",
+                "import fp from 'lodash/fp'"
             ].map(fromModule)
         }
     },
     invalid: {
```
Comment (SpainTrain) [inline tests/lib/rules/import-scope.js]: Arguably this shouldn't be testing the invalid/true positive cases since true positives for `lodash/fp` may be more in the wheelhouse of https://github.com/jfmengels/eslint-plugin-lodash-fp

LMK and I can nix these and just test that the false positives are fixed.

File: src/util/importUtil.js [hunk 2]
```diff
@@ -8,12 +8,12 @@ function getNameFromCjsRequire(init) {
 }
 
 
-const isFullLodashImport = str => /^lodash(-es)?$/.test(str)
+const isFullLodashImport = str => /^lodash(-es)?(\/fp)?$/.test(str)
```
Comment (ganimomer) [inline src/util/importUtil.js]: This solution would be problematic.
`importUtil` is used for `LodashContext`, which would mean that functions from `lodash/fp` would be recognized as Lodash functions by the plugin, and the rules don't consider `lodash/fp`, so there would be a lot of unforeseen consequences because of parameter order, currying etc.
That's why [`eslint-plugin-lodash-fp`](https://github.com/jfmengels/eslint-plugin-lodash-fp) is a separate plugin.
I would solve this by a RegExp that matches Lodash functions **but not `lodash/fp` functions**.

File: tests/lib/rules/import-scope.js (hunk 1 above)
Comment (ganimomer) [inline tests/lib/rules/import-scope.js]: You're right.
This plugin doesn't support `lodash/fp`, so this rule shouldn't warn against these cases. If anything, there should be tests with `lodash/fp` in the *valid* section, to make sure the rule doesn't warn against them.

File: src/util/importUtil.js (hunk 2 above)
Comment (SpainTrain) [inline src/util/importUtil.js]: Makes sense.  Should have dug in a bit more, but now I know.  :+1:

File: tests/lib/rules/import-scope.js (hunk 1 above)
Comment (SpainTrain) [inline tests/lib/rules/import-scope.js]: Good point :+1:

**Comment by SpainTrain** [comment]
@ganimomer updates complete, thanks for the review and pointers!

**Comment by SpainTrain** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wix/eslint-plugin-lodash/135)*

**Comment by ganimomer** [comment]
Looks great! Thanks for all the effort.

**Comment by SpainTrain** [comment]
:heart: 

Thanks for maintaining the plugin!  We love it.
